[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store"
